name: Pull Request automations

on: pull_request_target

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add size label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: |
            .gitignore
            *.md
            *.MD
            *.json
            *.sql
            .dockerignore
            LICENSE
        with:
          sizes: >
            {
              "0": "XS",
              "50": "S",
              "250": "M",
              "500": "L",
              "1000": "XL",
              "2000": "XXL"
            }

  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}